---
docker_container: 'my-container'
docker_image_name: 'nabiull2020/moscow-time-flask-app'
docker_image_version: 'latest'
docker_image: "{{ docker_image_name }}:{{ docker_image_version }}"
internal_port: 8000
external_port: 8000