version: "3"

networks:
  inner_network:

x-logging: &logger
  driver: "json-file"
  options:
    max-size: "64m"
    max-file: "2"
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

x-healthcheck: &healthcheck
  interval: 15s
  timeout: 5s
  retries: 3
  start_period: 3s

services:
  python_app:
    image: nabiull2020/moscow-time-flask-app:latest
    container_name: python_app
    ports:
      - "8000:8000"
    networks:
      - inner_network
    deploy:
        resources:
          limits:
            memory: 256m
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --timeout=1 http://localhost:8000/healthz || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logger

  c_sharp_app:
    image: nabiull2020/programmer-profile-asp-net:latest
    container_name: c_sharp_app
    ports:
      - "8080:80"
    networks:
      - inner_network
    deploy:
        resources:
          limits:
            memory: 256m
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --timeout=1 http://localhost:80/healthz || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logger

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - inner_network
    deploy:
        resources:
          limits:
            memory: 256m
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --timeout=1 http://localhost:3100/ready || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logger

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./configs/promtail:/etc/promtail/configs
    command: -config.file=/etc/promtail/configs/promtail.yaml
    networks:
      - inner_network
    deploy:
        resources:
          limits:
            memory: 256m
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9080' || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logger

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - inner_network
    deploy:
        resources:
          limits:
            memory: 512m
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --timeout=1 http://localhost:3000/api/health || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logger

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./configs/prometheus:/etc/prometheus
    command: '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    networks:
      - inner_network
    deploy:
      resources:
        limits:
          memory: 512m
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider --timeout=1 http://localhost:9090/-/healthy || exit 1"]
      <<: *healthcheck
    logging:
      <<: *logger