apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: moscow.time
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-app
                port:
                  number: 8000
    - host: programmer.profile
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: c-sharp-app
                port:
                  number: 80