name: PYTHON_APP_CI

on:
  push:
    paths:
      - 'app_python/**'
      - '.github/workflows/app_python.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Dependencies install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linter
        run: |
          pylint app.py --disable=missing-module-docstring --disable=missing-class-docstring --disable=missing-function-docstring
          pylint ./tests --disable=missing-module-docstring --disable=missing-class-docstring --disable=missing-function-docstring

      - name: Tests
        run: |
          python -m unittest discover -s tests -p '*_tests.py'

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moscow-time-flask-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/moscow-time-flask-app:latest